# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e207c4113bdf633087a96429cd62f86ea83c2102d3f278f1d113893b881d803c1b7ede7818d84cac75fe014fc969b36d2939403b45af0017ba20caa5a7d5caa

test:
  secret_key_base: 7705e5f8d3ae1f0b5c8c3c0a75afa358c4816285a38e51fbda8a344588ef1dcb5a2b020dd3ca70226eb09435aa84aa645c8e66b433ce88c40081062f291a04ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
